addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts:
      - github.com
      - 118.193.213.247
before_script:
  - echo -e 'Host 118.193.213.247\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
  - ssh-keyscan -H -t rsa,dsa -p 21521 118.193.213.247 >> ~/.ssh/known_hosts
script:
  - rsync -avz --exclude .git/ -e 'ssh -p 21521' ./ haochen@118.193.213.247:/home/haochen/site/root/www/
  - curl "https://api.keycdn.com/zones/purge/$CDN_ZONE_ID.json" -u $CDN_API:
